### ISSUE TITLE
Configuration file format specification

### ISSUE THREAD

**Issue by 1sra3l** [igorfs10/rust_hero#14]
The current file is:
```toml
name = "Knight"
hp = 50
mp = 20
atk = 20
def = 20
m_atk = 20
m_def = 20
exp = 0
img_idle = "knight.png"
img_walking = ""
img_attacking = ""
playable = true
```
You mentioned making all characters playable, so `playable = true` would seem not to be needed.  An "image" section would make more sense for TOML-style formats.  
```toml
[image]
idle = "knight.png"
walking = "knight_walk.png"
attacking = "knight_attack.png"
```
but as I mentioned in `rpgstat` building animations as another header would look like this in TOML:
```toml
[animations]
left =  { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
right = { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
up = { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
down =  { one = "/path/to/image", two = "/path/to/image", three = "/path/to/image", four = "/path/to/image"}
```
Once we have the human readable TOML format fields specified, it should be easy to implement {reading from, writing to} other formats.
the `rpgstat` ini files have more information possible, but do not need to be used:

```toml
[Knight]
name = "Ike"
# do we want descriptions?
short_description = "A  protector of the `Governmental` class"
long_description = ""
id = 0
hp = 50
mp = 20
xp = 1
hp_max = 50
mp_max = 20
xp_next = 10
gp = 10
speed = 7
atk = 20
def = 20
m_atk = 20
m_def = 20
# haven't been configured yet...
agi = 10
str = 10
int = 10
dex = 10
con = 10
char = 10
wis = 10
age = 10
```

The other thought would be to make the assets their own repository, once the file format is completed.  This could allow for me to just work on art without always needing you to accept the commit.  You could just submodule it, that way.  It would be easier to consolodate characters and we could list each group in the main `list.toml` file.
```toml
characters = "Knight.toml" # ...
enemies = "Rat".toml #...
rare = "EasterBilby.toml" #...
bosses = "SantaClaus.toml" #... 
# etc...
```
We would also need to use the format for "Items"  and things like `hp = 50` would be used to calculate the hp increase.

**Comment by igorfs10** [comment]
@1sra3l Yeah I'll remove the playable flag.

I agree, it's better to have a section for animation(images), I think we just have to add a struct to it.
``` I want description to create a bestiary. 😛```

I agree with a new repository, I just need one or two files to test. You can create your own and after I compile the game I will just need to copy files from repository.

The problem with groups in the list will be to use it in the location file to set the enemies. We will need to use an enum to make it work that way.

```
name = 'Forest'
description = ''
enemies_id = [
    0,
    1,
    2,
    3,
]
item_id = 0
background_img = 'assets/backgrounds/forest.png'
```

For items 

Will turn into

```
name = 'Forest'
description = ''
enemies_id = [
    enemies(0),
    enemies(1),
    enemies(2),
    boss(0),
]
item_id = 0
background_img = 'assets/backgrounds/forest.png'
```

What you think about it?

For items we can use the struct I have, but change the effect with an enum like the attack.
```
pub enum ItemEffect {
    Heal(u16), // Base number that we can use with mana attribute to set the amount to heal
    AtkUP(u16), //Percentage to improve atk
    RemoveStatusAilment(Type), //We can create an enum for this
}
```

For these things to work I think it's better to migrate to RON format that can deal with enums, what you think?
https://github.com/ron-rs/ron

**Comment by 1sra3l** [comment]
Created initial [libre-creatures](https://github.com/1sra3l/libre-creatures) repo.  I am just currently generating all of the files via [make_legendary.sh](https://github.com/1sra3l/libre-creatures/blob/main/make_legendary.sh) so we can quickly change the format initially.  Once we settle on it I can remove the script, or modify it to write in a different place.

The short/long description are there for your `bestiary`  I want Rust Hero to catch things and train them at some point :smile_cat: 

Here is my current format test with `[animation]`
```toml
name = "Easter Bilby"
short_description = "Easter Bilby – Anthropomorphic bilby."
long_description = "Bilbies are native Australian marsupials that are endangered. To raise money and increase awareness of conservation efforts, bilby-shaped chocolates and related merchandise are sold within many stores throughout Australia as an alternative to Easter bunnies.  The first documented use of the Easter Bilby concept was in March 1968 when a 9-year-old girl Rose-Marie Dusting, wrote a story, 'Billy The Aussie Easter Bilby,' which she published as a book 11 years later. The story helped catalyse the public's interest in saving the bilby. In 1991, Nicholas Newland from the 'Foundation for Rabbit-Free Australia' also developed the idea of the Easter Bilby to raise awareness about the environmental damage that feral rabbits cause and to replace the Easter bunny with true native wildlife.  The first Chocolate Easter Bilbies were sold at the Warrawong Sanctuary when it was owned by John Wamsley"
[stats]
id = 358
hp = 10
mp = 10
xp = 10
hp_max = 10
mp_max = 10
xp_next = 10
gp = 10
speed = 10
level = 0
atk = 10
def = 10
m_atk = 10
m_def = 10
agility = 10
strength = 10
intelligence = 10
dexterity = 10
constitution = 10
charisma = 10
wisdom = 10
age = 10
[animation]
walk = { right = "EasterBilby_walk_right.png", left = "EasterBilby_walk_left.png", up = "EasterBilby_walk_up.png", down = "EasterBilby_walk_down.png" }
attack = { right = "EasterBilby_attack_right.png", left = "EasterBilby_attack_left.png", up = "EasterBilby_attack_up.png", down = "EasterBilby_attack_down.png" }
special = { right = "EasterBilby_special_right.png", left = "EasterBilby_special_left.png", up = "EasterBilby_special_up.png", down = "EasterBilby_special_down.png" }

```

**Comment by 1sra3l** [comment]
For items, I am not sure if that is the best.  If we give items a stat, we can increase any stat easily, or even decrease them, by giving the stats a negative value.
```rs
let mut stats = rpgstat::stats::Normal<f64>::default();
# hp down
stats.hp = -15.0;
# mp up
stats.mp += 1.0;
# level up
stats.level += 1.0;
# whatever other effects
```
We could make the item more like
```rs
pub Item {
  pub name:String,
  pub duration:f64,
  pub effect:EffectType,
  pub stats:Stats,
}
```
toml for item will be
```toml
name = "thing"
# forever = 0, otherwise probably use Milliseconds
duration = 0
effect = "EffectFromEnum"
[stats]
# everything 0 except what you change
```

I think this gives much more flexibility in the future, so we create lots of items with lots of effects
